# Read the Docs configuration file for Molecule Benchmarks
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  jobs:
    post_create_environment:
      # Install uv
      - pip install uv
    post_install:
      # Install dependencies with uv
      - uv sync --group docs --group dev

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/source/conf.py
  builder: html
  fail_on_warning: false

# Optional but recommended, serve docs locally with MkDocs
# mkdocs:
#   configuration: mkdocs.yml

# Optionally build your docs in additional formats such as PDF and ePub
formats:
  - pdf
  - epub

# Optional but recommended if you have a Python package to import
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs
